#!/usr/bin/env node
// outlive -- run a command detached from the calling process tree.
//
// Why this exists: a coding agent that launches a long command as a descendant
// of itself can lose that command to any kill aimed at its own process tree.
// On this machine a ~14 minute Playwright suite died at roughly the 10 minute
// mark, every time, in the foreground, in the background, and under
// nohup + disown alike. The same command run by hand in a terminal completed.
// The variable is the process tree, not the machine or the suite.
//
// `nohup` and `disown` do not help: they change signal disposition and job
// control, not membership. A process stays in the tree it was born in.
//
// `launchctl submit` does move the job out of the tree, and on macOS it also
// moves it into launchd's privacy context -- which has no access to
// ~/Documents, ~/Desktop or ~/Downloads, cannot be widened from inside the
// job, and has no UI session to show a prompt on. A repo under ~/Documents
// therefore fails silently: exit 126, a 0-byte log, and a wait loop blocking
// on an exit file that is never written.
//
// So detach with setsid instead. `spawn(..., { detached: true })` gives the
// child its own session and process group and reparents it to PID 1 when this
// launcher exits -- the same escape from the tree, except the child is still
// this process's fork, so the responsible process for file access is unchanged.

import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync, openSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Single-quote for /bin/sh: wrap in ', close-escape-reopen each literal '.
export function shQuote(value) {
	return `'${String(value).replaceAll("'", `'\\''`)}'`;
}

// The command's last acts write the exit code and a finished stamp. A caller
// cannot tell "finished" from "stalled" by watching log output, so give it a
// file that only exists once the command is genuinely done.
export function buildWrapper({ runDir, cwd, argv }) {
	const command = argv.map(shQuote).join(' ');
	return `#!/bin/sh
# Generated by outlive. Regenerated per run; not for editing.
cd ${shQuote(cwd)} || exit 99
date -u +%Y-%m-%dT%H:%M:%SZ > ${shQuote(path.join(runDir, 'started'))}
${command} < /dev/null
echo $? > ${shQuote(path.join(runDir, 'exit'))}
date -u +%Y-%m-%dT%H:%M:%SZ > ${shQuote(path.join(runDir, 'finished'))}
`;
}

// kill(pid, 0) throws ESRCH when the process is gone. Used so a run that was
// killed cannot block the next one forever.
export function isAlive(pid) {
	try {
		process.kill(pid, 0);
		return true;
	} catch {
		return false;
	}
}

export function start(argv, { runDir = path.resolve('.outlive'), cwd = process.cwd() } = {}) {
	const pidPath = path.join(runDir, 'pid');
	if (existsSync(pidPath) && !existsSync(path.join(runDir, 'exit'))) {
		const prev = Number.parseInt(readFileSync(pidPath, 'utf8').trim(), 10);
		if (Number.isFinite(prev) && isAlive(prev)) {
			const err = new Error(`a run is already in flight (pid ${prev}). Stop it with: kill ${prev}`);
			err.code = 'EINFLIGHT';
			throw err;
		}
	}

	rmSync(runDir, { recursive: true, force: true });
	mkdirSync(runDir, { recursive: true });

	const wrapper = path.join(runDir, 'run.sh');
	const logPath = path.join(runDir, 'run.log');
	const errPath = path.join(runDir, 'run.err');
	writeFileSync(wrapper, buildWrapper({ runDir, cwd, argv }), { mode: 0o755 });

	// detached: true => setsid. Own session and process group, so a kill aimed
	// at this launcher's tree cannot reach it; reparents to PID 1 once we exit.
	// stdio goes straight to file descriptors -- a pipe nobody reads fills at
	// ~64KB and blocks the child forever, which looks exactly like a hang.
	const child = spawn('/bin/sh', [wrapper], {
		detached: true,
		stdio: ['ignore', openSync(logPath, 'a'), openSync(errPath, 'a')]
	});
	child.unref(); // or this launcher waits on it, and nothing was gained
	if (typeof child.pid !== 'number') throw new Error('failed to spawn the detached run');
	writeFileSync(pidPath, `${child.pid}\n`);

	return { pid: child.pid, runDir, logPath, errPath, exitPath: path.join(runDir, 'exit') };
}

function main() {
	const argv = process.argv.slice(2);
	if (argv.length === 0 || argv[0] === '--help' || argv[0] === '-h') {
		console.log('Usage: outlive <command> [args...]      (run dir: $OUTLIVE_DIR or ./.outlive)');
		process.exit(argv.length === 0 ? 1 : 0);
	}

	let run;
	try {
		run = start(argv, { runDir: path.resolve(process.env.OUTLIVE_DIR || '.outlive') });
	} catch (e) {
		console.error(`outlive: ${e.message}`);
		process.exit(1);
	}

	console.log(`Detached (pid ${run.pid}, own session, reparents to PID 1).`);
	console.log(`  command:  ${argv.join(' ')}`);
	console.log(`  stdout:   ${run.logPath}`);
	console.log(`  stderr:   ${run.errPath}`);
	console.log('');
	console.log('Block on the result:');
	console.log(`  until [ -f ${run.exitPath} ]; do sleep 20; done; echo "exit=$(cat ${run.exitPath})"`);
	console.log('');
	console.log(`Stop it early:  kill ${run.pid}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
