#!/usr/bin/env node
// outlive -- run a command detached from the calling process tree.
//
// spawn(..., { detached: true }) = setsid: the child gets its own session and
// process group, out of reach of any kill aimed at this launcher's tree, and
// reparents to PID 1 once the launcher exits. Unlike `launchctl submit`, the
// child is still this process's fork, so macOS keeps the same responsible
// process for file access and the repo stays readable. Full story: README.md.

import { spawn } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync, existsSync, openSync, rmSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

// Single-quote for /bin/sh: wrap in ', close-escape-reopen each literal '.
export function shQuote(value) {
	return `'${String(value).replaceAll("'", `'\\''`)}'`;
}

export function isAlive(pid) {
	try {
		process.kill(pid, 0);
		return true;
	} catch {
		return false;
	}
}

// The exit file is the caller's sentinel. Log output cannot distinguish
// "finished" from "stalled"; a file written as the command's last act can.
function wrapperScript(runDir, cwd, argv) {
	const runFile = (name) => shQuote(path.join(runDir, name));
	return `#!/bin/sh
# Generated by outlive. Regenerated per run; not for editing.
cd ${shQuote(cwd)} || exit 99
date -u +%Y-%m-%dT%H:%M:%SZ > ${runFile('started')}
${argv.map(shQuote).join(' ')} < /dev/null
echo $? > ${runFile('exit')}
date -u +%Y-%m-%dT%H:%M:%SZ > ${runFile('finished')}
`;
}

function inFlightPid(runDir) {
	const pidPath = path.join(runDir, 'pid');
	if (!existsSync(pidPath) || existsSync(path.join(runDir, 'exit'))) return null;
	const pid = Number.parseInt(readFileSync(pidPath, 'utf8'), 10);
	return Number.isFinite(pid) && isAlive(pid) ? pid : null;
}

export function start(argv, { runDir = path.resolve('.outlive'), cwd = process.cwd() } = {}) {
	const pid = inFlightPid(runDir);
	if (pid !== null) {
		const err = new Error(`a run is already in flight (pid ${pid}). Stop it with: kill ${pid}`);
		err.code = 'EINFLIGHT';
		throw err;
	}

	rmSync(runDir, { recursive: true, force: true });
	mkdirSync(runDir, { recursive: true });

	const wrapper = path.join(runDir, 'run.sh');
	const logPath = path.join(runDir, 'run.log');
	const errPath = path.join(runDir, 'run.err');
	writeFileSync(wrapper, wrapperScript(runDir, cwd, argv), { mode: 0o755 });

	// stdio must be real file descriptors: a pipe nobody reads fills at ~64KB
	// and blocks the child forever, which looks exactly like a hang.
	const child = spawn('/bin/sh', [wrapper], {
		detached: true,
		stdio: ['ignore', openSync(logPath, 'a'), openSync(errPath, 'a')]
	});
	child.unref(); // or this launcher waits on the child and stays in the tree
	if (typeof child.pid !== 'number') throw new Error('failed to spawn the detached run');
	writeFileSync(path.join(runDir, 'pid'), `${child.pid}\n`);

	return { pid: child.pid, runDir, logPath, errPath, exitPath: path.join(runDir, 'exit') };
}

const usage = 'Usage: outlive <command> [args...]      (run dir: $OUTLIVE_DIR or ./.outlive)';

function main() {
	const argv = process.argv.slice(2);
	if (argv[0] === '--help' || argv[0] === '-h') {
		console.log(usage);
		return;
	}
	if (argv.length === 0) {
		console.error(usage);
		process.exit(1);
	}

	let run;
	try {
		run = start(argv, { runDir: path.resolve(process.env.OUTLIVE_DIR || '.outlive') });
	} catch (e) {
		console.error(`outlive: ${e.message}`);
		process.exit(1);
	}

	console.log(`Detached (pid ${run.pid}, own session, reparents to PID 1).
  command:  ${argv.join(' ')}
  stdout:   ${run.logPath}
  stderr:   ${run.errPath}

Block on the result:
  until [ -f ${run.exitPath} ]; do sleep 20; done; echo "exit=$(cat ${run.exitPath})"

Stop it early:  kill ${run.pid}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
